version: '3'

services:
   {CONTAINER_DB}:
     image: mysql:5.7
     container_name: {CONTAINER_DB}
     volumes:
       - ./mysql/suntime:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: {MYSQL_PASSWORD}
       MYSQL_DATABASE: {MYSQL_NAME}
       MYSQL_USER: {MYSQL_USER}
       MYSQL_PASSWORD: {MYSQL_PASSWORD}
     networks:
        - {NETWORK}
#     deploy:
#       resources:
#         limits:
#           cpus: '{CPUS_WEB}'
#           memory: {MEM_WEB}

   {CONTAINER_WEB}:
     links:
       - {CONTAINER_DB}
     image: wordpress:5.3 
     container_name: {CONTAINER_WEB}
     volumes:
       - ./html:/var/www/html
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     restart: always
     {PORT_WEB}
        {PORT_MAPPING_WEB}
     environment:
       WORDPRESS_DB_HOST: {MYSQL_HOST}
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_PASSWORD: {MYSQL_PASSWORD}
       {VIRTUAL_HOST}
     networks:
        - {NETWORK}
#     deploy:
#       resources:
#         limits:
#           cpus: '{CPUS_DB}'
#           memory: {MEM_DB}
networks:
  {NETWORK}:
     external: true

