version: '3'

services:
   {NAME}-db:
     image: mysql:5.7
     container_name: {NAME}-db
     volumes:
       - ./mysql/suntime:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: {MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: {MYSQL_PASSWORD}
     networks:
        - nginx
   {NAME}-web:
     links:
       - {NAME}-db
     image: wordpress:4.9
     container_name: {NAME}-web
     volumes:
       - ./html:/var/www/html
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     restart: always
     environment:
       VIRTUAL_HOST: {VIRTUAL_HOST}
       WORDPRESS_DB_HOST: {NAME}-db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_PASSWORD: {WORDPRESS_DB_PASSWORD}
       REMOTE_ADDR: http://127.0.0.1:8080/
     networks:
        - nginx

networks:
  nginx:
     external: true

